### ISSUE TITLE
"|" as pattern

### ISSUE THREAD

**Issue by yellowhat** [RRethy/nvim-align#2]
Hi,
I am able to replicate the example using the "=" pattern.
Instead if I use the "|" one nothing happens:
```
| a | b |
|---|---|
| 10 | 20|
```

Does "|" need to be escaped in some way?

Thanks

**Comment by RRethy** [comment]
What specifically are you passing as the argument? To me, your example looks like it's already aligned on the first `|` of each line.

**Comment by yellowhat** [comment]
In my `.config/nvim/init.lua` I have add:
```
require("align")
vim.cmd [[
     command! -range=% -nargs=1 Align lua require("align").align(<f-args>)
]]
```

In visual mode select the lines and then run `:'<,'>Align |`.

**Comment by yellowhat** [comment]
Yes, you a re right, it aligns only the first "pattern".

**Comment by RRethy** [comment]
It supports regex, so you could do `:'<,'>Align [ -]\zs|`
