### ISSUE TITLE
Align skips non-ascii characters

### ISSUE THREAD

**Issue by PowerUser64** [RRethy/nvim-align#3]
I have noticed that when I try formatting text with characters containing accents (ex: á, ó, ú), Align seems to skip them as characters, leading to uneven alignment.

For example, I have this text:
```md
| el árbol | tree |
| el ave | bird |
| la ecología | ecology |
| el cielo | sky |
```
after selecting the text and doing `:'<,'>Align \ |\ ` and `:'<,'>Align \ |$`, I am left with
```md
| el árbol    | tree    |
| el ave       | bird    |
| la ecología | ecology |
| el cielo     | sky     |
```
As you can see, each line containing a character with an accent is missing a space, as if the accented characters don't exist.

\-\-\-

Another case with some odd behavior is this:
```md
| áóñò | íùöü |
| foo | bar |

```
Performing the same actions listed above results in this:
```md
| áóñò | íùöü |
| foo      | bar      |
```

Here, accented characters seem to be counted as two characters, which is odd because it doesn't seem to align with what is observed in the first example.

**Comment by RRethy** [comment]
The accented characters are 2 bytes wide, you can see this by looking at their utf8 encoding.

**Comment by PowerUser64** [comment]
Thank you for fixing this!
